### ISSUE TITLE
Test freezes when using Jest options `--runInBand` or `--maxWorkers 1`

### ISSUE THREAD

**Issue by kayahr** [kayahr/jest-electron-runner#1]
When running Jest with only a single concurrent process (By using `--runInBand` or `--maxWorkers 1`) then the second test suite run with jest-electron-runner just hangs. It works when using at least two workers.

This can even be reproduced with the jest-electron-runner tests itself. Simply create a second test suite (Duplicating the existing one) and then run `npm run check -- --maxWorkers 1`

**Comment by der-ranjit** [comment]
when will this be fixed? i'm waiting for at least a minute now!

**Comment by byzanth** [comment]
This is a critical issue for us. Please fix this fast!

**Comment by kayahr** [comment]
With co-workers like you who needs enemies...

**Comment by kayahr** [comment]
Fixed in v4.4.0
